apiVersion: batch/v1
kind: Job
metadata:
  name: hello-00013
  namespace: takeyama-test
spec:
  template:
    spec:
      containers:
        - name: hello
          image: ruby
          command:
            [
              "ruby",
              "-e",
              '10.times { |n| warn "Hello: #{n}"; sleep 1 }; exit 3',
            ]
      restartPolicy: Never
  backoffLimit: 4
